stages:
  preprocess:
    cmd: clj -X preprocess/do-preprocess
    deps:
      - src/preprocess.clj
      - deps.edn
      - train.csv
      - test.csv
    outs:
      - train.arrow
      - test.arrow


  train:
    cmd: ./train.sh
    deps:
      - src/train.clj
      - deps.edn
      - train.arrow
      - test.arrow
    #outs:
    metrics:
      - eval.json
    params:
      - train.top-n


  # predict_kaggle:
  #    cmd: clj -X predict_kaggle/predict-kaggle
  #    deps:
  #      - deps.edn
  #      - outputs
  #      - src/predict_kaggle.clj
  #    outs:
  #      - kaggle_submission.csv

# plots:
#   outputs/training_progress_scores.csv:
#     x: global_step
#     y:
#       - train_loss
#       - eval_loss
